# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_txt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Disp(object):
    def setupUi(self, Dialog_Disp):
        Dialog_Disp.setObjectName("Dialog_Disp")
        Dialog_Disp.resize(721, 610)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_Disp)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser_Disp = QtWidgets.QTextBrowser(Dialog_Disp)
        self.textBrowser_Disp.setObjectName("textBrowser_Disp")
        self.gridLayout.addWidget(self.textBrowser_Disp, 0, 0, 1, 1)
        self.pushButton_DIsp_Done = QtWidgets.QPushButton(Dialog_Disp)
        self.pushButton_DIsp_Done.setObjectName("pushButton_DIsp_Done")
        self.gridLayout.addWidget(self.pushButton_DIsp_Done, 1, 0, 1, 1)

        self.retranslateUi(Dialog_Disp)
        self.pushButton_DIsp_Done.clicked.connect(Dialog_Disp.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Disp)

    def retranslateUi(self, Dialog_Disp):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Disp.setWindowTitle(_translate("Dialog_Disp", "Dialog"))
        self.pushButton_DIsp_Done.setText(_translate("Dialog_Disp", "Done"))
