# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgsnewhttpconnectionbase.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qgsnewhttpconnectionbase(object):
    def setupUi(self, qgsnewhttpconnectionbase):
        qgsnewhttpconnectionbase.setObjectName("qgsnewhttpconnectionbase")
        qgsnewhttpconnectionbase.resize(642, 153)
        self.gridLayout = QtWidgets.QGridLayout(qgsnewhttpconnectionbase)
        self.gridLayout.setObjectName("gridLayout")
        self.label_NewSrvName = QtWidgets.QLabel(qgsnewhttpconnectionbase)
        self.label_NewSrvName.setObjectName("label_NewSrvName")
        self.gridLayout.addWidget(self.label_NewSrvName, 0, 0, 1, 1)
        self.txt_NewSrvName = QtWidgets.QLineEdit(qgsnewhttpconnectionbase)
        self.txt_NewSrvName.setEnabled(True)
        self.txt_NewSrvName.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txt_NewSrvName.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.txt_NewSrvName.setObjectName("txt_NewSrvName")
        self.gridLayout.addWidget(self.txt_NewSrvName, 0, 1, 1, 1)
        self.label_NewSrvUrl = QtWidgets.QLabel(qgsnewhttpconnectionbase)
        self.label_NewSrvUrl.setObjectName("label_NewSrvUrl")
        self.gridLayout.addWidget(self.label_NewSrvUrl, 1, 0, 1, 1)
        self.txt_NewSrvUrl = QtWidgets.QLineEdit(qgsnewhttpconnectionbase)
        self.txt_NewSrvUrl.setObjectName("txt_NewSrvUrl")
        self.gridLayout.addWidget(self.txt_NewSrvUrl, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(qgsnewhttpconnectionbase)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)

        self.retranslateUi(qgsnewhttpconnectionbase)
        self.buttonBox.accepted.connect(qgsnewhttpconnectionbase.accept) # type: ignore
        self.buttonBox.rejected.connect(qgsnewhttpconnectionbase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(qgsnewhttpconnectionbase)

    def retranslateUi(self, qgsnewhttpconnectionbase):
        _translate = QtCore.QCoreApplication.translate
        qgsnewhttpconnectionbase.setWindowTitle(_translate("qgsnewhttpconnectionbase", "New WCS Server "))
        self.label_NewSrvName.setText(_translate("qgsnewhttpconnectionbase", "Server Name"))
        self.label_NewSrvUrl.setText(_translate("qgsnewhttpconnectionbase", "Server URL"))
